## YAML Template.
name: Run Tests

on:
  workflow_dispatch:
    inputs:
      test-filter:
        description: 'Which tests to run (Maven -Dtest value)'
        required: false
        default: 'SmokeTests'
        type: choice
        options:
           - SmokeTests
           - VoiceTestSuite

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 17 * * *'


permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout

concurrency:
  group: deploy
  cancel-in-progress: false
  

jobs:
  run-tests-west:
    # Only run smoke tests in us-west-2
    if: >-
      ${{
        vars.RUN_TESTS &&
        (
          ((github.event_name == 'workflow_dispatch' && inputs.test-filter) || 'SmokeTests')
          == 'SmokeTests'
        )
      }}
    runs-on: ubuntu-latest
    environment: "us-west-2-tests"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Execute Tests (us-west-2)
        uses: ./.github/actions/test
        with:
          region: us-west-2
          stack-name: ${{ vars.STACK_NAME || 'spring-ai-square-ivr' }}
          aws-role: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          session-id: ${{ github.run_id }}-${{ github.run_attempt }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          spring-ai-model: ${{ vars.SPRING_AI_PROVIDER == 'OPENAI' && vars.OPENAI_MODEL || vars.BEDROCK_MODEL }}
          test-filter: ${{ (github.event_name == 'workflow_dispatch' && inputs.test-filter) || 'SmokeTests' }}
  run-tests-east:
    if: ${{ vars.RUN_TESTS }}
    runs-on: ubuntu-latest
    environment: "us-east-1-tests"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Execute Tests (us-east-1)
        uses: ./.github/actions/test
        with:
          region: us-east-1
          stack-name: ${{ vars.STACK_NAME || 'spring-ai-square-ivr' }}
          aws-role: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          session-id: ${{ github.run_id }}-${{ github.run_attempt }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          spring-ai-model: ${{ vars.SPRING_AI_PROVIDER == 'OPENAI' && vars.OPENAI_MODEL || vars.BEDROCK_MODEL }}
          test-filter: ${{ (github.event_name == 'workflow_dispatch' && inputs.test-filter) || 'SmokeTests' }}
