## YAML Template.
name: Run Tests

on:
  workflow_dispatch:
    inputs:
      test-filter:
        description: 'Which tests to run (Maven -Dtest value)'
        required: false
        default: 'SmokeTests'
        type: choice
        options:
           - SmokeTests
           - VoiceTestSuite

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 17 * * *'


permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout

concurrency:
  group: deploy
  cancel-in-progress: false
  

jobs:
  run-tests:
    # Runs once per matrix entry; this "if" is evaluated per matrix row
    if: >-
      ${{
        vars.RUN_TESTS &&
        (
          matrix.region == 'us-east-1' ||
          (
            ((github.event_name == 'workflow_dispatch' && inputs.test-filter) || 'SmokeTests')
            == 'SmokeTests'
          )
        )
      }}

    strategy:
      max-parallel: 1
      matrix:
        region: [us-west-2, us-east-1]

    runs-on: ubuntu-latest
    environment: "${{ matrix.region }}-tests"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Execute Tests
        uses: ./.github/actions/test
        with:
          region: ${{ matrix.region }}
          stack-name: ${{ vars.STACK_NAME || 'spring-ai-square-ivr' }}
          aws-role: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          session-id: ${{ github.run_id }}-${{ github.run_attempt }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          spring-ai-model: ${{ vars.SPRING_AI_PROVIDER == 'OPENAI' && vars.OPENAI_MODEL || vars.BEDROCK_MODEL }}
          test-filter: ${{ (github.event_name == 'workflow_dispatch' && inputs.test-filter) || 'SmokeTests' }}
